### ISSUE TITLE
Accessing training event metadata

### ISSUE THREAD

**Issue by nrmay** [nrmay/TeSS#18]
### Access the metadata in my registry in real time through an API
- [ ]  As a Registry administrator/manager, I want to be able to access the metadata in the National Training Registry in real time through an API (or scraper) in order to build views or services on other related platforms.

#### Search functionality for users 
- [ ] As a user (trainer, researcher, research support professional), I need search results that are relevant and based on search terms (relevance ranking), with most relevant results on the 1st page.
- [ ] As a user (trainer, researcher, research support professional), I would like to be able to search efficiently with Advanced Search functionality. ??
- [ ] As a user (trainer, researcher, research support professional), I would like to be able to search efficiently using Regular Expressions (include, exclude words etc) or Boolean search functionality.
- [ ] As a user (trainer, researcher, research support professional), when searching I would like to be able to easily report broken links.
- [ ] As a user (trainer, researcher, research support professional), I would like to have some auto suggest functionality to enable efficient searching.
- [ ] As a user (trainer, researcher, research support professional), I would like to have some functionality around tolerance for misspelling to enable efficient searching.
- [ ] As a user (trainer, researcher, research support professional), I would like to have some options for whole or partial search terms to enable efficient searching.
- [ ] As an institutional executive manager (funder of institutional training), I want to be able to track the training provided by my institution as well as others.
- [ ] As​ ​a​ ​user (researcher, research support professional), I want to be able to see all training events within my field/area of interest provided by my institution. 

### Filtering search for training events
- [ ] As a user (trainer, researcher, research support professional), I want to be able to filter my training event results to narrow the list to events that are of interest to me. Filter by:
   - Person (trainer)
   - Timeline
   - Training provider organisation
   - Search terms, keywords, categories, topic
   - Order by date (e.g. recent date)
   - Location / online
   - Cost
   - Other??

**Comment by KathrynU** [comment]
May want to have a look at the Search functionality issues for users
