### ISSUE TITLE
Trainer Profiles (Pass 1)

### ISSUE THREAD

**Issue by nrmay** [nrmay/TeSS#202]
- [x] new model:  **trainer**
  - [x] db migrations 
- [x] new controller: **trainer_controller**
- [x] new helper: **trainer_helper**
- [x] new policy: **trainer_policy** 
- [x] new serializer: **trainer_serializer**
- new views
  - [x] trainer/**index** (html & json)
  - [x] ~~trainer/**new** (html)~~
  - [x] trainer/**show** (html & json)
- new test cases
  - [x] **model**
  - [x] **controller**
  - [x] **helpers**
  - [x] etc. (integration & unit)
- general search
  - [x] add trainers tab
