### ISSUE TITLE
Stretch activities

### ISSUE THREAD

**Issue by nrmay** [nrmay/TeSS#22]
### Be identified by the registry to enable social networking
- [ ] As a user (trainer, researcher, research support professional), I want the National Training Registry to recognize me and others so that I can be connected with other users who I know, leave comments and be informed of training events that are of interest​ ​to​ ​me.

### Receive recommendations about resources of interest to me
- [ ] As​ ​a​ ​user (researcher, research support professional),​ ​I​ ​want​ ​to​ ​receive​ ​recommendations​ ​about​ training events ​that​ are​ ​of​ ​potential​ ​interest to​ ​me​ ​and​ ​related​ ​to​ ​my​ ​work,​ ​so​ ​I​ ​increase​ ​opportunities for skills development​ ​in​ ​my​ ​field.

### Discover registry training events of interest via aggregators or search services 
- [ ] As a user (trainer, researcher, research support professional), I want to discover registry training events of interest via aggregators or other search​ ​services​ ​such​ ​as​ ​Google.

**Comment by KathrynU** [comment]
I think we've covered the middle issue. 
The top one is maybe a step further than we need to go for networking trainers? 
The bottom one - is this already possible? If I was to do a search on Google for a specific training event in DReSA would it come up in Google?

**Comment by nrmay** [comment]
Re. google searches... yes our pages are indexed and searchable by google. However, we will usually appear lower than the original linked url.
eg: search for... qiime2 workshop introduction to metabarcoding
